In [8]:
import xarray as xr
import maskacc
import numpy as np

In [9]:
arr = np.random.rand(5,3,4)
cube = xr.DataArray(arr, dims=['band', 'a', 'b'], coords={'b':[3,4,5,6], 'band':[1,2,3,6,7], 'a':[1,2,3]})

In [10]:
cube.M.dims

['a', 'b']

In [15]:
cube.M.refresh(dims=['a', 'band'])

In [17]:
cube.M.mask

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
cube.M.refresh(dims=['a', 'b'])

In [19]:
cube.M.mask

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [20]:
cube.M.mask = np.array([[0,1,0,1],[1,0,1,0],[0,1,0,1]])

In [21]:
cube.M.mask

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [22]:
cube.M.select([0,0])
cube.M.mask

array([[1, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [26]:
cube.M.select([(0,2),(1,1)])
cube.M.mask

array([[1, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 0, 1]])

In [27]:
cube.M.selected_ones()
cube.M.mask

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
cube.M.selected_zeros()
cube.M.mask

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
cube.M.selected_ones()
cube.M.to_list()

[[0.35940897690218365,
  0.7991130903658499,
  0.1054573737528196,
  0.42660296856116176,
  0.9587907929181276],
 [0.9370344754448661,
  0.5814617496225783,
  0.8054580462666125,
  0.26227388062838397,
  0.13401394270554512],
 [0.9690330093813223,
  0.4662722991252828,
  0.8912607084170179,
  0.1535560857130599,
  0.1986624968990074],
 [0.9075877941443835,
  0.8359389302247247,
  0.4778647786067979,
  0.6500563608829947,
  0.43766206559322784],
 [0.019943930811941124,
  0.9750282062754586,
  0.9165660718778766,
  0.049414584066101885,
  0.6561629207807556],
 [0.32836454101754997,
  0.4713364111348438,
  0.7146790737945173,
  0.296718851107873,
  0.7909450957401664],
 [0.7157994345169424,
  0.8124654033446378,
  0.981887818761682,
  0.4023724744452438,
  0.18485711904592506],
 [0.5484242723230349,
  0.9461362040478855,
  0.867958099817634,
  0.5229651684647321,
  0.0636903777027753],
 [0.38931248491165893,
  0.7002111334599735,
  0.5309679233291242,
  0.6914911720081729,
  0.53953841821

In [34]:
cube.M.selected_zeros()
cube.M.select([(0,0),(0,1),(0,2)])
cube.M.where_masked()

<xarray.DataArray (band: 5, a: 1, b: 3)>
array([[[ 0.359409,  0.937034,  0.969033]],

       [[ 0.799113,  0.581462,  0.466272]],

       [[ 0.105457,  0.805458,  0.891261]],

       [[ 0.426603,  0.262274,  0.153556]],

       [[ 0.958791,  0.134014,  0.198662]]])
Coordinates:
  * b        (b) int32 3 4 5
  * band     (band) int32 1 2 3 6 7
  * a        (a) int32 1

In [35]:
cube.M.mask_as_xarray()

<xarray.DataArray (a: 3, b: 4)>
array([[1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
Coordinates:
  * b        (b) int32 3 4 5 6
    band     int32 1
  * a        (a) int32 1 2 3

In [36]:
cube.M.shape

(3, 4)